##########################################################################################################
# This configuration will install the tools necessary to get started with Python development on Windows  #
# Reference: https://learn.microsoft.com/windows/python/beginners                                        #
#                                                                                                        #
# This will:                                                                                             #
#     * SDK Dotnet 8                                                                                     #
#     * Install BuildTools                                                                               #
#     * Install Rustup                                                                                   #
#     * Install VCRedist 2015+.x64                                                                       #
#                                                                                                        #
##########################################################################################################
schemaVersion: 1.0.0
packages:
  - packageIdentifier: Microsoft.VisualStudio.2022.BuildTools
    version: latest
  - packageIdentifier: Microsoft.DotNet.SDK.8
    version: latest
  - packageIdentifier: Rustlang.Rustup
    version: latest
  - packageIdentifier: Microsoft.VCRedist.2015+.x64
    version: latest
uninstall:
  - Microsoft.Edge
  - OneDrive
settings:
  theme: dark
  language: en-US
